#!/usr/bin/env python
# Copyright (C) 2014-2017 Catherine Beauchemin <cbeau@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =============================================================================

import numpy
import phymcmc.mcmc
import sys

def add_biological_params( pdic ):
	biodic = {}
	# Basic reproductive number
	biodic['R0'] = pdic['p']*pdic['b']*pdic['N']*pdic['tI']/pdic['c']
	# Infecting time (h)
	biodic['tinf'] = numpy.sqrt(2.0*pdic['N']/pdic['p']/pdic['b'])
	# Half-life (h)
	biodic['chalf'] = numpy.log(2.0)/pdic['c']
	# SSR = -2*lnprob [unless base_model.get_lnprob overwritten by user model]
	biodic['ssr'] = -2.0*pdic['lnprob']
	return biodic

# Read chain_file name from command-line (1st argument)
chainfile = sys.argv[1]
# Push biological params into chainfile
phymcmc.mcmc.add_derived_dict_to_mcmc_chain( add_biological_params, chainfile )
