#!/usr/bin/env python
# Copyright (C) 2014-2021 Catherine Beauchemin <cbeau@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =============================================================================

import baccam
import numpy
import phymcmc.fits
import phymcmc.plot

dat = numpy.loadtxt("baccam.dat")
dathpi = dat[:,0]
datV = dat[:,1]
# This is possibly be the standard deviation of the data replicates
#   (where applicable) or the 68% error bars (if you have those).
#   If you have neither, you can use the mean of the residuals between
#   your model's best fit (once found... iterate!) and the data
#   which is why it's ok as 1.0 for fitting but should be set to
#   the correct value when running MCMC because the normalized SSR
#   is required to calculate the likelihood = exp[-ssr/(2*stdev^2)]
#   where stdev here is called "sigV".
sigV = 1.0
# Your data
# (feel free to pack other non-varying arguments in there)
dat = (dathpi,datV,sigV)

pdic = dict(
	Vlim = 10.0**0.5, # Limit of detection for V
	N = 4.0e8,	# Ncells as per paper
	tI = 24.0, nI=16,
	p = datV.max()*0.1/4.0e8,
	c = 0.1,
	b = 1.0/datV.max(),
	V0 = datV[0]
)
pfit = ['p','c','b','V0']

# Create params structure
params = baccam.params(pdic.copy(),pfit)

# Grab model instance
model = baccam.model(dat, params)

# Fit model to data
params,lnprob = phymcmc.fits.perform_fit(model,verbose=True)

# Solve and save results
t = numpy.linspace(0.0,7.5*24.0)
res = model.get_solution(t)
mV = numpy.hstack((numpy.matrix(t).T,res))
numpy.savetxt('soln_V.dat', mV)
# Plot it too?
if True:
	gridfig = phymcmc.plot.grid_plot((1,1),rwidth=4.0)
	ax = gridfig.subaxes(0)
	ax.semilogy(dathpi/24.0,datV,'s')
	ax.semilogy(t/24.0,res[:,0],'k-')
	ax.set_ylabel(r'Viral titer (TCID$_{50}$/mL)')
	ax.set_ylim(10.0**-2.2,10.0**8.1)
	ax.set_xlabel('time post-infection (days)')
	ax.set_xlim(0.0,7.5)
	gridfig.fig.savefig('soln_V.pdf', bbox_inches='tight')
