#!/usr/bin/env python
# Copyright (C) 2014 Catherine Beauchemin <cbeau@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#

import phymbie.mcmc
import sys

#
# =============================================================================
#
#                                   Utilities
#
# =============================================================================
#

def add_biological_params( pdic ):
	biodic = {}
	N = 1.2e6
	Volume = 0.5
	# Example of a computed biological parameter (add as many as you want)
	biodic['slotyint'] = pdic['slope']*pdic['yint']/Volume/N
	return biodic

#
# =============================================================================
#
#                                   Main
#
# =============================================================================
#

# Read chain_file name from command-line (1st argument)
chainfile = sys.argv[1]
# Push biological params into chainfile
phymbie.mcmc.add_derived_dict_to_mcmc_chain( add_biological_params, chainfile )
