#!/usr/bin/env python
# Copyright (C) 2014-2016 Catherine Beauchemin <cbeau@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#

import linmod
import numpy
import phymcmc.fits

#
# =============================================================================
#
#                                   Main
#
# =============================================================================
#

dat = numpy.loadtxt("lin.dat")

# Would either load params or initialize and fit
pdic = dict(slope=1.0,yint=1.0)
pfit = ['slope','yint']

# Now fit the parameters
params = phymcmc.ParamStruct(pdic.copy(),pfit)
params,bfssr = phymcmc.fits.perform_fit(linmod.model,params,dat,verbose=True,rep_fit=3)
