#!/usr/bin/env python
# Copyright (C) 2014-2021 Catherine Beauchemin <cbeau@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#

import linmod
import numpy
import phymcmc.fits

#
# =============================================================================
#
#                                   Main
#
# =============================================================================
#

# Your data
# (feel free to pack other non-varying arguments in dat)
dat = numpy.loadtxt("lin.dat")

# Initial value for all model parameters
pdic = dict(slope=1.0,yint=1.0)
# List of parameters that are to be estimated
#  (need not be all of them)
pfit = ['slope','yint']

# Create the params structure
params = linmod.params(pdic.copy(),pfit)

# Grab model instance
model = linmod.line(dat, params)

# Now look for params that will maximize the ln(probability)
params,lnprob = phymcmc.fits.perform_fit(model,verbose=True,nreps=3)

# Get best solution and plot it too?
if True:
	import phymcmc.plot
	x = numpy.linspace(dat[0,0]-1,dat[-1,0]+1)
	res = model.get_solution(x)
	gridfig = phymcmc.plot.grid_plot((1,1),rwidth=4.0)
	ax = gridfig.subaxes(0)
	ax.plot(dat[:,0],dat[:,1],'s')
	ax.plot(x,res,'k-')
	gridfig.fig.savefig('soln_linmod.pdf', bbox_inches='tight')
