#!/usr/bin/python
import linmod
import numpy
import phymbie.fits
import phymbie.mcmc

dat = numpy.loadtxt("lin.dat")

# Centre location from which to launch walkers
# 	should normally be the output of a best-fit to start in good place
pdic = dict(slope=1.0,yint=1.0)
pfit = ['slope','yint']
params = phymbie.fits.ParamStruct(pdic.copy(),pfit)

# MCMC parameters
mcpars = dict(
	chain_file = 'outputs/chain_lin.hdf5',
	model = linmod.model,
	nwalkers = 300,
	nsteps = 400,
	nburn = 0,
	par = params,
	# Parameters over which walkers will be linearly distributed initially
	# Note that all parameters will be walked in LINEAR space
	linpars = ['ssr', 'slope', 'yint'],
	# Arguments (args) passed to lnpostfn such that lnpostfn(pvec,par,args)
	args = dat,
	threads = 4
)

# Setting up the MCMC sampler
mcsampler = phymbie.mcmc.MCSampler( **mcpars )
# Performing the MCMC run
mcsampler.run_mcmc()
