#!/usr/bin/env python
# Copyright (C) 2014-2019 Catherine Beauchemin <cbeau@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =============================================================================

import os
import phymcmc.plot

chainfile = os.path.abspath('chain_lin.hdf5')

labeldic = {
	'lnprob': r'lnLikelihood',
	'ssr': r'Sum squared resid, SSR',
	'slope': r'slope, $m$',
	'yint': r'$y_\mathrm{int}$',
	'slotyint': r'Weird meaningless par'
}
allpars = ['ssr','slope','yint','slotyint']

# Example of making histogram grid of all params
colours = ['blue']
plotlabels = [labeldic[key] for key in allpars]
gridfig = phymcmc.plot.hist_grid( [chainfile], parlist=allpars, labels=plotlabels, colors=colours, dims=(1,4), nburn=200 )
# Adjust some params
ax = gridfig.fig.axes[allpars.index('yint')]
ax.set_xlim(7.8,9.0)
ax = gridfig.fig.axes[allpars.index('slotyint')]
ax.set_xlim(110.0,140.0)
ax.set_xscale('linear')
gridfig.fig.savefig('hists_lin.pdf', bbox_inches='tight')
