#!/usr/bin/env python
# Copyright (C) 2014-2016 Catherine Beauchemin <cbeau@users.sourceforge.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#

import os
import phymcmc.plot

#
# =============================================================================
#
#                                   Main
#
# =============================================================================
#

chainfile = os.path.abspath('chain_lin.hdf5')

labeldic = {
	'ssr': r'Sum squared resid, SSR',
	'slope': r'slope, $m$',
	'yint': r'$y_\mathrm{int}$',
	'slotyint': r'Weird meaningless par'
}
allpars = ['ssr','slope','yint','slotyint']

# Making triangle plot of param pairs
if True:
	plotpars = allpars[:-1]
	plotlabels = plotpars
	fig = phymcmc.plot.triangle(plotpars, plotlabels, chainfile)
	# Make PDF from PNG otherwise PDF is too big
	import subprocess
	fig.savefig('triangle_lin.png', bbox_inches='tight')
	subprocess.call('convert triangle_lin.png triangle_lin.pdf', shell=True)
	subprocess.call('rm -f triangle_lin.png', shell=True)

# Making histogram grid of all params
if True:
	colors = ['blue']
	plotpars = allpars
	plotlabels = [labeldic[key] for key in plotpars]
	gridfig = phymcmc.plot.hist_grid(plotpars, [chainfile], colors, dims=(1,4), labels=plotlabels)
	gridfig.fig.savefig('hists_lin.pdf', bbox_inches='tight')

